server.port: 8080

spring.jpa:
  hibernate.ddl-auto=none

spring.datasource:
  url: jdbc:hsqldb:mem:testdb
  driverClassName: org.hsqldb.jdbcDriver
  username: sa
  password:
  initialize: true
  data: classpath:/db/data.sql
  schema: classpath:/db/schema.sql